"""Report generation: markdown, json, csv."""

import csv
import json
from datetime import datetime, timezone
from pathlib import Path

from .scoring import verdict


def to_markdown(results: list[dict], source_file: str) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# Enrichment Report - `{source_file}`",
        f"Generated: {now} · Tool: phishlab v1.1 (enrich.py)",
        "",
        "| IOC (refanged display) | Type | Score | Verdict | Key signals |",
        "|---|---|---|---|---|",
    ]
    for r in results:
        disp = r["value"].replace("http://", "hxxp://").replace("https://", "hxxps://").replace(".", "[.]").replace("@", "[@]")
        sig = "; ".join(r["reasons"]) if r["reasons"] else "no hits"
        lines.append(f"| {disp} | {r['type']} | {r['score']} | {verdict(r['score'])} | {sig} |")
    lines += ["", "## Per-IOC detail", ""]
    for r in results:
        lines.append(f"### {r['value']} ({r['type']}) - {r['score']}/100")
        lines.append(f"- Verdict: {verdict(r['score'])}")
        if r.get("flags"):
            lines.append(f"- Heuristics: {', '.join(r['flags'])}")
        for src in ("vt", "abuse", "otx"):
            lines.append(f"- {src}: {r.get(src, {})}")
        # urlscan optional
        if "urlscan" in r:
            lines.append(f"- urlscan: {r.get('urlscan', {})}")
        lines.append("")
    top = max(results, key=lambda x: x["score"]) if results else None
    lines.append("## Overall recommendation")
    if top:
        lines.append(f"- Highest score: {top['score']} ({top['value']}) → {verdict(top['score'])}")
        if top["score"] >= 75:
            lines.append("- Action: **Block + Incident** - quarantine, reset creds, revoke sessions, EDR 24h.")
        elif top["score"] >= 40:
            lines.append("- Action: **Escalate Tier-2** - attach this report + header + timeline.")
        else:
            lines.append("- Action: **Monitor / Close as FP** - consider allowlist, user education.")
    else:
        lines.append("- No IOCs extracted.")
    lines.append("")
    lines.append("Note: Generated by `phishlab`. Defanged IOCs are safe to share. Re-run with live keys to replace `skipped` sources.")
    return "\n".join(lines)


def to_json(results: list[dict], source_file: str) -> str:
    payload = {
        "source": source_file,
        "generated": datetime.now(timezone.utc).isoformat(),
        "tool": "phishlab v1.1",
        "results": results,
        "summary": {
            "count": len(results),
            "highest": max(results, key=lambda x: x["score"]) if results else None,
        },
    }
    return json.dumps(payload, indent=2)


def write_csv(results: list[dict], out_path: str) -> None:
    fieldnames = ["value", "type", "score", "verdict", "reasons", "flags", "vt", "abuse", "otx"]
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for r in results:
            w.writerow({
                "value": r["value"],
                "type": r["type"],
                "score": r["score"],
                "verdict": verdict(r["score"]),
                "reasons": "; ".join(r.get("reasons", [])),
                "flags": ", ".join(r.get("flags", [])),
                "vt": str(r.get("vt", {})),
                "abuse": str(r.get("abuse", {})),
                "otx": str(r.get("otx", {})),
            })


def save_all(results: list[dict], source_file: str, md_path: str | None = None, json_path: str | None = None, csv_path: str | None = None) -> None:
    if md_path:
        Path(md_path).parent.mkdir(parents=True, exist_ok=True)
        Path(md_path).write_text(to_markdown(results, source_file), encoding="utf-8")
    if json_path:
        Path(json_path).parent.mkdir(parents=True, exist_ok=True)
        Path(json_path).write_text(to_json(results, source_file), encoding="utf-8")
    if csv_path:
        Path(csv_path).parent.mkdir(parents=True, exist_ok=True)
        write_csv(results, csv_path)
